name: Mocha

on:
  workflow_run:
    workflows:
      - EditorConfig
      - ESLint
      - Prettier
    types:
      - completed
  pull_request:
    branches:
      - main
    paths:
      - 'specs/**/*.spec.js'
      - 'src/**/*.js'
  push:
    branches:
      - main
    paths:
      - 'specs/**/*.spec.js'
      - 'src/**/*.js'

jobs:
  mocha:
    name: Test

    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          cache: npm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Tests
        run: npm run test
